### ISSUE TITLE
mvn build issues

### ISSUE THREAD

**Issue by johncallahan** [bcgov/did-auth-relying-party#1]
I'm not the best maven person, but I'm pretty sure something needs to be added to the README for connecting to the bcgov specific jar files references in the pom.xml file.  Thanks!

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building did-auth-relying-party 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for fi.trustnet:verifiable-credentials-java:jar:0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for decentralized-identity:uni-resolver-client:jar:0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.263 s
[INFO] Finished at: 2018-03-21T16:48:48-04:00
[INFO] Final Memory: 10M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project did-auth-relying-party: Could not resolve dependencies for project ca.bcgov.didauth:did-auth-relying-party:war:0.1-SNAPSHOT: The following artifacts could not be resolved: fi.trustnet:verifiable-credentials-java:jar:0.1-SNAPSHOT, decentralized-identity:uni-resolver-client:jar:0.1-SNAPSHOT: Could not find artifact fi.trustnet:verifiable-credentials-java:jar:0.1-SNAPSHOT -> [Help 1]

**Comment by peacekeeper** [comment]
Yes this project requires several dependencies that are not yet available in Maven and have to be built manually. I'll add instructions for this to the README.
